Add reviews to films
tonasd/java-filmorate pull request #7
Opened 2023-03-31 12:23 UTC by nix-pix

2023-03-31 13:44 UTC, Vanchey359 approved these changes
Ошибок не нашел)

2023-03-31 14:49 UTC, tonasd requested changes

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review updateReview(@RequestBody Review review) {
Можно в апдейт запихнуть ревью с некорректными данными. Здесь тоже нужно валидировать как и в предыдущем методе.

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @DeleteMapping("/{id}")
Кажется здесь и далее проще было сразу запихнуть в эдпойнт "/{reviewId}"  чем потом во всех методах дополнительно писать у аннотации @PathVariable критерий name = "id"

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviewService.getReviewsByFilmId(filmId, count);
Хм, тут почему-то логгирования не видно.

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                          @PathVariable("userId") long userId) {
Здесь и далее указание "userId" кажется избыточным, но для процесса обучения наверно самое оно :)

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDao.java
> +    Review putLike(long reviewId, Long userId);
Здесь и в следующем Long userId , а в остальных long userId. Зачем такая вариативность?

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +@Getter
А зачем здесь геттер и сеттер?

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public Review update(Review review) throws ReviewNotFoundException {
Здесь кажется можно и без throws ReviewNotFoundException обойтись поскольку наследуется от RuntimeException это исключение.

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public Review update(Review review) throws ReviewNotFoundException {
Но наличие такой подписи это может и не плохо, а может и хорошо.

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            } catch (EmptyResultDataAccessException e) {
Получается если убирать из объявления методов throws ReviewNotFoundException (учитывая что оно наследовано от рантаймЭксептион) то можно не писать вот такие try{} catch блоки

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            } catch (EmptyResultDataAccessException e) {
В данном случае у метода getReviewById

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        Review review = getReviewById(reviewId);
У тебя же есть метод isReviewExist, можно было им пользоваться здесь (это явно не ошибка, просто так кажется логичнее)

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        if (isReviewExist(reviewId)) {
Здесь можно лаконичнее:
            try {
                String sql = "SELECT * FROM REVIEWS WHERE REVIEW_ID = ?";
                return jdbcTemplate.queryForObject(sql, new ReviewRowMapper(), reviewId);
            } catch (EmptyResultDataAccessException e) {
                throw ReviewNotFoundException("Неверно указан id = " + reviewId + " отзыва");
            }

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        if (isReviewExist(reviewId)) {
if убрать совсем

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public List<Review> getReviewsByFilmId(long filmId, int count) {
В этом методе идёт потеря разделения ответственности.
1. count значение по умолчанию 10 уже прописано в контроллере, здесь эта проверка кажется лишней.
2. filmId почему если номер фильма не дан выводятся только 10 отзывов, а не все. По заданию кажется в таком случае нужно все выводить.

2023-03-31 14:49 UTC, tonasd commented on src/main/resources/schema.sql
> +    IS_USEFUL BOOLEAN,
Нигде в коде не используется, наверно лишнее поле

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        String sqlLike = "INSERT INTO REVIEWS_USERS (REVIEW_ID, USER_ID) VALUES (?, ?)";
Здесь наверно была идея, чтобы один и тот-же юзер не мог ставить много лайков на одно и то-же ревью, но не вижу реализации. Нет проверки на то, что лайк уже был от этого юзера. Наверное БД будет ругаться на одинаковые строки, но там нет проверки на то, чтобы не было дубликатов. Только если сам H2 это делает по умолчанию.
Здесь я не знаю точно, это пока мысли вслух. Но кажется лучше вручную явно добавить нужные проверки.

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        String sqlLike = "INSERT INTO REVIEWS_USERS (REVIEW_ID, USER_ID) VALUES (?, ?)";
Аналогично как у лайка

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        String sqlLike = "INSERT INTO REVIEWS_USERS (REVIEW_ID, USER_ID) VALUES (?, ?)";
А вообще кажется крутая доработка про которую нет в задании, но она кажется логичной.

2023-03-31 14:49 UTC, tonasd commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +@RequiredArgsConstructor
Получается, что в объекте нет полей final а значит эту аннотацию можно заменить на @NoArgsConstructor

2023-03-31 14:49 UTC, tonasd commented on src/main/resources/schema.sql
> -CREATE TABLE IF NOT EXISTS PUBLIC.AGE_RESTRICTION_RATINGS (
А можно не вносить такие изменения, мы потом заманаемся решать конфликт при том, что его (конфликта) как такового и нет.
Просьба вернуть все create к их первоначальному CREATE виду

2023-03-31 14:49 UTC, tonasd commented on src/main/resources/schema.sql
> +	CONSTRAINT FILM_DIRECTOR_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON delete CASCADE,
и тут delete к его первоначальному DELETE

2023-03-31 14:49 UTC, tonasd commented on src/main/resources/schema.sql
> +    IS_USEFUL BOOLEAN,
И получается, что вся таблица является не используемой по сути. 
Наверно нужно либо реализовать идею до какого -то рабочего состояния, либо просто удалить это.

2023-03-31 14:49 UTC, tonasd commented on src/test/postman-tests-add-reviews.json
Этот файл кажется тут лишний. Его можно не индексировать и не коммитить.

2023-03-31 19:26 UTC, nix-pix commented on src/main/resources/schema.sql
> +    IS_USEFUL BOOLEAN,
таблица используется для лайков и дислайков

2023-04-02 07:34 UTC, tonasd commented on src/main/resources/schema.sql
> -CREATE TABLE IF NOT EXISTS PUBLIC.AGE_RESTRICTION_RATINGS (
Вот здесь просьба всё-же поменять на прописные, как было изначально в develop

2023-04-02 07:35 UTC, tonasd commented on src/main/resources/schema.sql
> +	CONSTRAINT FILM_DIRECTOR_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON delete CASCADE,
И здесь прошу поменять назад к прописным буквам.

2023-04-02 09:32 UTC, tonasd approved these changes

2023-04-02 09:33 UTC, merged